# -*- coding: utf-8 -*-
"""Modulo6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDa4IDcXVWaBF-ikLWplw59dVnvbxDt-

Modulo 5
"""

# ============================================
# PROYECTO: HÁBITOS SALUDABLES EN JÓVENES UNIVERSITARIOS
# ANÁLISIS ESTADÍSTICO COMPLETO
# ============================================

# Instalar librerías necesarias (ejecutar solo una vez)
!pip install faker pandas numpy matplotlib seaborn scipy plotly -q

# Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import norm, t, binom, poisson
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Configuración de visualización
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print("="*60)
print("ANÁLISIS DE HÁBITOS SALUDABLES - JÓVENES UNIVERSITARIOS")
print("="*60)

# ============================================
# 1. GENERACIÓN DEL DATASET SIMULADO
# ============================================

# Semilla para reproducibilidad
np.random.seed(42)

# Parámetros
n_estudiantes = 150  # Aumentamos a 150 para mejor análisis

# Facultades y proporciones
facultades = {
    'Ciencias de la Salud': 0.25,
    'Ingenierías': 0.35,
    'Ciencias Sociales': 0.25,
    'Humanidades': 0.15
}

# Sexo
sexos = ['Masculino', 'Femenino', 'Otro']
prob_sexo = [0.45, 0.50, 0.05]

# Generación de datos
data = {
    'ID': range(1, n_estudiantes + 1),
    'Edad': np.random.normal(21, 2.5, n_estudiantes).astype(int),
    'Sexo': np.random.choice(sexos, n_estudiantes, p=prob_sexo),
    'Facultad': np.random.choice(list(facultades.keys()), n_estudiantes,
                                 p=list(facultades.values())),
    'Semestre': np.random.randint(1, 11, n_estudiantes),
}

# Convertir a DataFrame
df = pd.DataFrame(data)

# Ajustar edades (entre 17 y 30 años)
df['Edad'] = df['Edad'].clip(17, 30)

# Variables dependientes con correlaciones
# Horas de sueño (distribución normal)
df['Horas_Sueno'] = np.random.normal(6.8, 1.2, n_estudiantes)
df.loc[df['Facultad'] == 'Ingenierías', 'Horas_Sueno'] -= 0.5
df.loc[df['Facultad'] == 'Ciencias de la Salud', 'Horas_Sueno'] += 0.3
df['Horas_Sueno'] = df['Horas_Sueno'].clip(4, 10).round(1)

# Horas de estudio
df['Horas_Estudio'] = np.random.normal(5.5, 2.0, n_estudiantes)
df.loc[df['Facultad'] == 'Ingenierías', 'Horas_Estudio'] += 1.0
df.loc[df['Facultad'] == 'Humanidades', 'Horas_Estudio'] -= 0.5
df['Horas_Estudio'] = df['Horas_Estudio'].clip(1, 12).round(1)

# Actividad física (minutos semanales)
df['AF_Minutos'] = np.random.exponential(150, n_estudiantes)
df.loc[df['Sexo'] == 'Masculino', 'AF_Minutos'] *= 1.2
df['AF_Minutos'] = df['AF_Minutos'].clip(0, 600).astype(int)

# Estrés (escala 1-10)
df['Estres'] = np.random.normal(6.5, 1.8, n_estudiantes)
df.loc[df['Horas_Estudio'] > 7, 'Estres'] += 1.5
df.loc[df['Horas_Sueno'] < 6, 'Estres'] += 1.0
df['Estres'] = df['Estres'].clip(1, 10).round(1)

# Comida rápida (días por semana)
df['Comida_Rapida'] = np.random.poisson(3, n_estudiantes)
df.loc[df['Estres'] > 7, 'Comida_Rapida'] += 1
df['Comida_Rapida'] = df['Comida_Rapida'].clip(0, 7)

# IMC
df['IMC'] = np.random.normal(23.5, 3.5, n_estudiantes)
df.loc[df['Comida_Rapida'] > 4, 'IMC'] += 2.0
df.loc[df['AF_Minutos'] > 200, 'IMC'] -= 1.5
df['IMC'] = df['IMC'].clip(16, 35).round(1)

# Variables categóricas derivadas
df['AF_Regular'] = df['AF_Minutos'].apply(lambda x: 'Sí' if x >= 150 else 'No')
df['Consume_Alcohol'] = np.random.choice(['Sí', 'No'], n_estudiantes, p=[0.6, 0.4])
df['Fuma'] = np.random.choice(['Sí', 'No'], n_estudiantes, p=[0.15, 0.85])
df['Tipo_Alimentacion'] = np.random.choice(['Omnívoro', 'Vegetariano', 'Vegano'],
                                           n_estudiantes, p=[0.7, 0.2, 0.1])
df['Turno'] = np.random.choice(['Diurno', 'Nocturno'], n_estudiantes, p=[0.8, 0.2])

# Calidad de sueño (categórica)
df['Calidad_Sueno'] = pd.cut(df['Horas_Sueno'],
                             bins=[0, 6, 7.5, 10],
                             labels=['Malo', 'Regular', 'Bueno'])

print("\n✅ DATASET CREADO EXITOSAMENTE")
print(f"Dimensiones: {df.shape[0]} filas × {df.shape[1]} columnas")

# ============================================
# 2. DICCIONARIO DE VARIABLES
# ============================================

diccionario = pd.DataFrame({
    'Variable': [
        'ID', 'Edad', 'Sexo', 'Facultad', 'Semestre', 'Horas_Sueno',
        'Horas_Estudio', 'AF_Minutos', 'Estres', 'Comida_Rapida',
        'IMC', 'AF_Regular', 'Consume_Alcohol', 'Fuma',
        'Tipo_Alimentacion', 'Turno', 'Calidad_Sueno'
    ],
    'Tipo': [
        'Cuantitativa discreta', 'Cuantitativa discreta', 'Cualitativa nominal',
        'Cualitativa nominal', 'Cuantitativa discreta', 'Cuantitativa continua',
        'Cuantitativa continua', 'Cuantitativa discreta', 'Cuantitativa continua',
        'Cuantitativa discreta', 'Cuantitativa continua', 'Cualitativa nominal',
        'Cualitativa nominal', 'Cualitativa nominal', 'Cualitativa nominal',
        'Cualitativa nominal', 'Cualitativa ordinal'
    ],
    'Descripción': [
        'Identificador único del estudiante', 'Edad en años', 'Sexo del estudiante',
        'Facultad a la que pertenece', 'Semestre actual', 'Horas de sueño diarias',
        'Horas de estudio diarias', 'Minutos de actividad física semanal',
        'Nivel de estrés percibido (1-10)', 'Días de comida rápida por semana',
        'Índice de Masa Corporal', '¿Realiza actividad física regular? (≥150 min)',
        '¿Consume alcohol?', '¿Fuma?', 'Tipo de alimentación',
        'Turno de estudio', 'Calidad de sueño (categorizada)'
    ],
    'Rango/Valores': [
        '1-150', '17-30', 'Masculino/Femenino/Otro',
        'Salud/Ingenierías/Sociales/Humanidades', '1-10', '4.0-10.0',
        '1.0-12.0', '0-600', '1.0-10.0', '0-7',
        '16.0-35.0', 'Sí/No', 'Sí/No', 'Sí/No',
        'Omnívoro/Vegetariano/Vegano', 'Diurno/Nocturno', 'Malo/Regular/Bueno'
    ]
})

print("\n" + "="*60)
print("DICCIONARIO DE VARIABLES")
print("="*60)
display(diccionario)

# ============================================
# 3. ANÁLISIS DESCRIPTIVO
# ============================================

# Estadísticas de variables numéricas
variables_numericas = ['Edad', 'Horas_Sueno', 'Horas_Estudio', 'AF_Minutos',
                       'Estres', 'Comida_Rapida', 'IMC']

estadisticas = df[variables_numericas].describe().round(2)
print("\n📊 ESTADÍSTICAS DESCRIPTIVAS - VARIABLES NUMÉRICAS")
print("="*60)
display(estadisticas)

# Matriz de correlación
print("\n📈 MATRIZ DE CORRELACIÓN")
print("="*60)
correlacion = df[variables_numericas].corr().round(3)
display(correlacion)

# Tablas de frecuencia para variables categóricas
variables_categoricas = ['Sexo', 'Facultad', 'AF_Regular', 'Consume_Alcohol',
                         'Fuma', 'Tipo_Alimentacion', 'Turno', 'Calidad_Sueno']

print("\n📊 TABLAS DE FRECUENCIA - VARIABLES CATEGÓRICAS")
print("="*60)
for var in variables_categoricas:
    print(f"\n{var}:")
    freq = df[var].value_counts()
    percent = df[var].value_counts(normalize=True).mul(100).round(1)
    tabla = pd.DataFrame({'Frecuencia': freq, 'Porcentaje': percent})
    display(tabla)

# ============================================
# 4. VISUALIZACIONES COMPLETAS (CON GUARDADO)
# ============================================

# 4.1 Histogramas de variables numéricas
fig = plt.figure(figsize=(20, 25))

for i, var in enumerate(variables_numericas, 1):
    plt.subplot(4, 2, i)

    # Histograma
    n, bins, patches = plt.hist(df[var], bins=15, edgecolor='black',
                                 alpha=0.7, color='skyblue', density=True)

    # Curva de densidad
    df[var].plot(kind='density', color='red', linewidth=2, ax=plt.gca())

    # Líneas de media y mediana
    plt.axvline(df[var].mean(), color='blue', linestyle='dashed',
                linewidth=2, label=f'Media: {df[var].mean():.2f}')
    plt.axvline(df[var].median(), color='green', linestyle='dashed',
                linewidth=2, label=f'Mediana: {df[var].median():.2f}')

    plt.title(f'Distribución de {var}', fontsize=12, fontweight='bold')
    plt.xlabel(var)
    plt.ylabel('Densidad')
    plt.legend()
    plt.grid(True, alpha=0.3)

plt.suptitle('DISTRIBUCIONES DE VARIABLES NUMÉRICAS', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('01_histogramas_completos.png', dpi=300, bbox_inches='tight')  # Guardado
plt.show()
print("✅ Gráfico 1 guardado: 01_histogramas_completos.png")

# 4.2 Boxplots por facultad
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
axes = axes.ravel()

variables_box = ['Horas_Sueno', 'Horas_Estudio', 'AF_Minutos', 'Estres', 'Comida_Rapida', 'IMC']

for i, var in enumerate(variables_box):
    sns.boxplot(data=df, x='Facultad', y=var, ax=axes[i])
    axes[i].set_title(f'{var} por Facultad', fontweight='bold')
    axes[i].tick_params(axis='x', rotation=45)

plt.suptitle('DISTRIBUCIÓN DE VARIABLES POR FACULTAD', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('02_boxplots_completos.png', dpi=300, bbox_inches='tight')  # Guardado
plt.show()
print("✅ Gráfico 2 guardado: 02_boxplots_completos.png")

# 4.3 Gráficos de barras para variables categóricas
fig, axes = plt.subplots(2, 4, figsize=(20, 12))
axes = axes.ravel()

variables_categoricas = ['Sexo', 'Facultad', 'AF_Regular', 'Consume_Alcohol',
                         'Fuma', 'Tipo_Alimentacion', 'Turno', 'Calidad_Sueno']

for i, var in enumerate(variables_categoricas):
    counts = df[var].value_counts()
    axes[i].bar(counts.index, counts.values, color=sns.color_palette("husl", len(counts)))
    axes[i].set_title(f'Distribución de {var}', fontweight='bold')
    axes[i].tick_params(axis='x', rotation=45)

    # Agregar valores en las barras
    for j, v in enumerate(counts.values):
        axes[i].text(j, v + 1, str(v), ha='center', fontweight='bold')

plt.suptitle('VARIABLES CATEGÓRICAS', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('03_barras_categoricas.png', dpi=300, bbox_inches='tight')  # Guardado
plt.show()
print("✅ Gráfico 3 guardado: 03_barras_categoricas.png")

# 4.4 Mapa de calor de correlaciones
plt.figure(figsize=(12, 10))
mask = np.triu(np.ones_like(correlacion, dtype=bool))
sns.heatmap(correlacion, mask=mask, annot=True, cmap='coolwarm', center=0,
            square=True, linewidths=1, cbar_kws={"shrink": .8}, fmt='.2f')
plt.title('MAPA DE CALOR - CORRELACIONES ENTRE VARIABLES NUMÉRICAS',
          fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('04_mapa_calor_correlaciones.png', dpi=300, bbox_inches='tight')  # Guardado
plt.show()
print("✅ Gráfico 4 guardado: 04_mapa_calor_correlaciones.png")

# 4.5 Gráficos de dispersión con tendencias
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Sueño vs Estrés
sns.scatterplot(data=df, x='Horas_Sueno', y='Estres', hue='Facultad',
                size='AF_Minutos', sizes=(20, 200), alpha=0.6, ax=axes[0,0])
sns.regplot(data=df, x='Horas_Sueno', y='Estres', scatter=False,
            color='red', ax=axes[0,0])
axes[0,0].set_title('Relación: Sueño vs Estrés', fontweight='bold')

# Estudio vs Sueño
sns.scatterplot(data=df, x='Horas_Estudio', y='Horas_Sueno', hue='Sexo',
                style='AF_Regular', alpha=0.6, ax=axes[0,1])
sns.regplot(data=df, x='Horas_Estudio', y='Horas_Sueno', scatter=False,
            color='green', ax=axes[0,1])
axes[0,1].set_title('Relación: Estudio vs Sueño', fontweight='bold')

# IMC vs Comida rápida
sns.boxplot(data=df, x='Comida_Rapida', y='IMC', ax=axes[1,0])
axes[1,0].set_title('IMC por consumo de comida rápida', fontweight='bold')

# Actividad física vs IMC
sns.scatterplot(data=df, x='AF_Minutos', y='IMC', hue='Sexo',
                size='Edad', sizes=(20, 200), alpha=0.6, ax=axes[1,1])
sns.regplot(data=df, x='AF_Minutos', y='IMC', scatter=False,
            color='purple', ax=axes[1,1])
axes[1,1].set_title('Relación: Actividad Física vs IMC', fontweight='bold')

plt.suptitle('ANÁLISIS DE RELACIONES BIVARIADAS', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('05_dispersion_completa.png', dpi=300, bbox_inches='tight')  # Guardado
plt.show()
print("✅ Gráfico 5 guardado: 05_dispersion_completa.png")

# ============================================
# 5. ANÁLISIS DE PROBABILIDAD
# ============================================

print("\n" + "="*60)
print("ANÁLISIS DE PROBABILIDAD")
print("="*60)

# Definir eventos
n_total = len(df)

# Evento A: Duerme menos de 6 horas
evento_A = df[df['Horas_Sueno'] < 6]
p_A = len(evento_A) / n_total

# Evento B: Actividad física regular
evento_B = df[df['AF_Regular'] == 'Sí']
p_B = len(evento_B) / n_total

# Evento C: Comida rápida frecuente (≥4 días/semana)
evento_C = df[df['Comida_Rapida'] >= 4]
p_C = len(evento_C) / n_total

# Evento D: Alto estrés (≥7)
evento_D = df[df['Estres'] >= 7]
p_D = len(evento_D) / n_total

print(f"\n📊 PROBABILIDADES SIMPLES:")
print(f"P(A) = P(Duerme < 6h) = {p_A:.3f} ({p_A*100:.1f}%)")
print(f"P(B) = P(AF Regular) = {p_B:.3f} ({p_B*100:.1f}%)")
print(f"P(C) = P(Comida rápida ≥4) = {p_C:.3f} ({p_C*100:.1f}%)")
print(f"P(D) = P(Estrés ≥7) = {p_D:.3f} ({p_D*100:.1f}%)")

# Intersecciones
A_y_B = len(df[(df['Horas_Sueno'] < 6) & (df['AF_Regular'] == 'Sí')]) / n_total
A_y_C = len(df[(df['Horas_Sueno'] < 6) & (df['Comida_Rapida'] >= 4)]) / n_total
B_y_D = len(df[(df['AF_Regular'] == 'Sí') & (df['Estres'] >= 7)]) / n_total

print(f"\n📊 PROBABILIDADES DE INTERSECCIÓN:")
print(f"P(A∩B) = {A_y_B:.3f}")
print(f"P(A∩C) = {A_y_C:.3f}")
print(f"P(B∩D) = {B_y_D:.3f}")

# Probabilidades condicionales
print(f"\n📊 PROBABILIDADES CONDICIONALES:")
print(f"P(A|B) = P(Duerme<6 | AF Regular) = {A_y_B/p_B:.3f}")
print(f"P(B|A) = P(AF Regular | Duerme<6) = {A_y_B/p_A:.3f}")
print(f"P(C|D) = P(Comida rápida | Alto estrés) = {A_y_C/p_D:.3f}")

# Árbol de probabilidad para estrés y actividad física
print(f"\n🌳 ÁRBOL DE PROBABILIDAD (Estrés vs Actividad Física):")
print(f"P(Bajo estrés) = {1-p_D:.3f}")
print(f"  ├─ P(AF Regular | Bajo estrés) = {len(df[(df['Estres'] < 7) & (df['AF_Regular'] == 'Sí')]) / len(df[df['Estres'] < 7]):.3f}")
print(f"  └─ P(No AF | Bajo estrés) = {len(df[(df['Estres'] < 7) & (df['AF_Regular'] == 'No')]) / len(df[df['Estres'] < 7]):.3f}")
print(f"P(Alto estrés) = {p_D:.3f}")
print(f"  ├─ P(AF Regular | Alto estrés) = {len(df[(df['Estres'] >= 7) & (df['AF_Regular'] == 'Sí')]) / len(df[df['Estres'] >= 7]):.3f}")
print(f"  └─ P(No AF | Alto estrés) = {len(df[(df['Estres'] >= 7) & (df['AF_Regular'] == 'No')]) / len(df[df['Estres'] >= 7]):.3f}")

# ============================================
# 6. DISTRIBUCIONES DE PROBABILIDAD
# ============================================

print("\n" + "="*60)
print("DISTRIBUCIONES DE PROBABILIDAD")
print("="*60)

# 6.1 Distribución Normal - Horas de sueño
mu_sueno = df['Horas_Sueno'].mean()
sigma_sueno = df['Horas_Sueno'].std()

print(f"\n📈 DISTRIBUCIÓN NORMAL - Horas de Sueño")
print(f"Media (μ) = {mu_sueno:.2f} horas")
print(f"Desviación estándar (σ) = {sigma_sueno:.2f} horas")

# Calcular probabilidades normales
x = np.linspace(mu_sueno - 4*sigma_sueno, mu_sueno + 4*sigma_sueno, 100)
y = norm.pdf(x, mu_sueno, sigma_sueno)

plt.figure(figsize=(12, 6))
plt.plot(x, y, 'b-', linewidth=2, label='Distribución normal teórica')
plt.hist(df['Horas_Sueno'], density=True, bins=15, alpha=0.6,
         color='skyblue', edgecolor='black', label='Datos reales')
plt.axvline(mu_sueno, color='red', linestyle='--', label=f'Media = {mu_sueno:.2f}')
plt.axvline(6, color='green', linestyle='--', label='Límite 6 horas')

# Áreas bajo la curva
x_fill = np.linspace(4, 6, 50)
y_fill = norm.pdf(x_fill, mu_sueno, sigma_sueno)
plt.fill_between(x_fill, y_fill, alpha=0.3, color='red', label=f'P(X<6) = {norm.cdf(6, mu_sueno, sigma_sueno):.3f}')

plt.title('DISTRIBUCIÓN NORMAL - HORAS DE SUEÑO', fontsize=14, fontweight='bold')
plt.xlabel('Horas de sueño')
plt.ylabel('Densidad de probabilidad')
plt.legend()
plt.grid(True, alpha=0.3)

# GUARDAR GRÁFICO 1
plt.savefig('06_distribucion_normal_sueno.png', dpi=300, bbox_inches='tight')
print("✅ Gráfico guardado: 06_distribucion_normal_sueno.png")
plt.show()

print(f"P(X < 6 horas) = {norm.cdf(6, mu_sueno, sigma_sueno):.3f}")
print(f"P(7 < X < 8 horas) = {norm.cdf(8, mu_sueno, sigma_sueno) - norm.cdf(7, mu_sueno, sigma_sueno):.3f}")

# 6.2 Distribución Binomial - Comida rápida
n_dias = 7
p_comida = df['Comida_Rapida'].mean() / n_dias

print(f"\n📈 DISTRIBUCIÓN BINOMIAL - Días de comida rápida")
print(f"n = {n_dias} días")
print(f"p = {p_comida:.3f} probabilidad diaria")
print(f"λ = n*p = {n_dias * p_comida:.2f} días promedio")

# Valores posibles
x_binom = np.arange(0, 8)
y_binom = binom.pmf(x_binom, n_dias, p_comida)

plt.figure(figsize=(12, 6))
plt.bar(x_binom, y_binom, alpha=0.7, color='coral', edgecolor='black')
plt.axvline(df['Comida_Rapida'].mean(), color='red', linestyle='--',
            label=f'Media observada = {df["Comida_Rapida"].mean():.2f}')

plt.title('DISTRIBUCIÓN BINOMIAL - DÍAS DE COMIDA RÁPIDA', fontsize=14, fontweight='bold')
plt.xlabel('Número de días con comida rápida')
plt.ylabel('Probabilidad')
plt.xticks(x_binom)
plt.legend()
plt.grid(True, alpha=0.3)

# GUARDAR GRÁFICO 2
plt.savefig('07_distribucion_binomial_comida.png', dpi=300, bbox_inches='tight')
print("✅ Gráfico guardado: 07_distribucion_binomial_comida.png")
plt.show()

print(f"P(X = 3 días) = {binom.pmf(3, n_dias, p_comida):.3f}")
print(f"P(X ≥ 5 días) = {1 - binom.cdf(4, n_dias, p_comida):.3f}")

# Prueba de normalidad (Shapiro-Wilk)
print(f"\n📊 PRUEBA DE NORMALIDAD (Shapiro-Wilk):")
for var in ['Horas_Sueno', 'Horas_Estudio', 'IMC']:
    statistic, p_value = stats.shapiro(df[var])
    print(f"{var}: estadístico={statistic:.3f}, p-valor={p_value:.3f}")
    if p_value > 0.05:
        print(f"  → Distribución normal (no se rechaza H0)")
    else:
        print(f"  → No sigue distribución normal (se rechaza H0)")

print("\n✅ SECCIÓN 6 COMPLETADA - Gráficos guardados:")
print("   • 06_distribucion_normal_sueno.png")
print("   • 07_distribucion_binomial_comida.png")

# ============================================
# 7. TEOREMA DEL LÍMITE CENTRAL
# ============================================

print("\n" + "="*60)
print("TEOREMA DEL LÍMITE CENTRAL")
print("="*60)

# Parámetros poblacionales
mu_pob = df['Horas_Sueno'].mean()
sigma_pob = df['Horas_Sueno'].std()
print(f"\nPoblación original (n={len(df)}):")
print(f"Media poblacional (μ) = {mu_pob:.3f}")
print(f"Desviación estándar poblacional (σ) = {sigma_pob:.3f}")

# Generar distribuciones muestrales
n_muestras = 1000
tamanos_muestra = [5, 10, 20, 30]

fig, axes = plt.subplots(2, 2, figsize=(15, 12))
axes = axes.ravel()

for idx, n in enumerate(tamanos_muestra):
    medias_muestrales = []

    for _ in range(n_muestras):
        muestra = np.random.choice(df['Horas_Sueno'], size=n, replace=True)
        medias_muestrales.append(np.mean(muestra))

    # Calcular estadísticos
    media_medias = np.mean(medias_muestrales)
    error_estandar = np.std(medias_muestrales)
    error_teorico = sigma_pob / np.sqrt(n)

    # Histograma
    axes[idx].hist(medias_muestrales, bins=30, density=True, alpha=0.7,
                   color='skyblue', edgecolor='black')

    # Curva normal teórica
    x = np.linspace(media_medias - 4*error_estandar, media_medias + 4*error_estandar, 100)
    y = norm.pdf(x, mu_pob, sigma_pob/np.sqrt(n))
    axes[idx].plot(x, y, 'r-', linewidth=2, label='Distribución normal')

    axes[idx].axvline(mu_pob, color='green', linestyle='--',
                      linewidth=2, label=f'μ poblacional = {mu_pob:.2f}')
    axes[idx].axvline(media_medias, color='blue', linestyle='--',
                      linewidth=2, label=f'μ muestral = {media_medias:.2f}')

    axes[idx].set_title(f'n = {n} (Error estándar: {error_estandar:.3f})',
                        fontweight='bold')
    axes[idx].set_xlabel('Media muestral')
    axes[idx].set_ylabel('Densidad')
    axes[idx].legend()
    axes[idx].grid(True, alpha=0.3)

    print(f"\nDistribución muestral (n={n}):")
    print(f"  Media de medias = {media_medias:.3f}")
    print(f"  Error estándar empírico = {error_estandar:.3f}")
    print(f"  Error estándar teórico (σ/√n) = {error_teorico:.3f}")
    print(f"  Diferencia: {abs(error_estandar - error_teorico):.3f}")

plt.suptitle('TEOREMA DEL LÍMITE CENTRAL - DISTRIBUCIONES MUESTRALES',
             fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()

# GUARDAR GRÁFICO
plt.savefig('08_teorema_limite_central.png', dpi=300, bbox_inches='tight')
print("\n✅ Gráfico guardado: 08_teorema_limite_central.png")
plt.show()

print("\n✅ SECCIÓN 7 COMPLETADA")

# ============================================
# 8. INTERVALOS DE CONFIANZA
# ============================================

print("\n" + "="*60)
print("INTERVALOS DE CONFIANZA")
print("="*60)

def calcular_ic(datos, variable, nivel_confianza=0.95):
    """Calcula intervalo de confianza para la media"""
    n = len(datos)
    media = np.mean(datos)
    desv_est = np.std(datos, ddof=1)
    error_est = desv_est / np.sqrt(n)

    # Valor crítico t
    gl = n - 1
    alfa = 1 - nivel_confianza
    t_critico = stats.t.ppf(1 - alfa/2, gl)

    margen = t_critico * error_est
    ic_inf = media - margen
    ic_sup = media + margen

    return {
        'variable': variable,
        'n': n,
        'media': media,
        'desv_est': desv_est,
        'error_est': error_est,
        'nivel_conf': nivel_confianza,
        't_critico': t_critico,
        'margen': margen,
        'ic_inf': ic_inf,
        'ic_sup': ic_sup
    }

# Calcular IC para diferentes variables y niveles
variables_ic = ['Horas_Sueno', 'Horas_Estudio', 'Estres', 'IMC']
niveles = [0.90, 0.95, 0.99]

resultados_ic = []

for var in variables_ic:
    for nivel in niveles:
        resultado = calcular_ic(df[var], var, nivel)
        resultados_ic.append(resultado)

        print(f"\n{var} - IC {nivel*100:.0f}%:")
        print(f"  Media = {resultado['media']:.2f}")
        print(f"  Error estándar = {resultado['error_est']:.3f}")
        print(f"  t crítico = {resultado['t_critico']:.3f}")
        print(f"  Margen = ±{resultado['margen']:.3f}")
        print(f"  IC = ({resultado['ic_inf']:.3f}, {resultado['ic_sup']:.3f})")
        print(f"  Amplitud = {resultado['ic_sup'] - resultado['ic_inf']:.3f}")

# Visualización de intervalos
fig, axes = plt.subplots(2, 2, figsize=(15, 12))
axes = axes.ravel()

colores = ['blue', 'green', 'red']
for idx, var in enumerate(variables_ic):
    datos_var = [r for r in resultados_ic if r['variable'] == var]

    for i, dato in enumerate(datos_var):
        nivel = dato['nivel_conf']
        y_pos = i
        axes[idx].errorbar(dato['media'], y_pos, xerr=[[dato['media']-dato['ic_inf']],
                                                       [dato['ic_sup']-dato['media']]],
                          fmt='o', color=colores[i], capsize=5,
                          label=f"{nivel*100:.0f}% IC")

    axes[idx].axvline(datos_var[0]['media'], color='black', linestyle='--',
                      alpha=0.5, label='Media muestral')
    axes[idx].set_yticks([0, 1, 2])
    axes[idx].set_yticklabels(['90%', '95%', '99%'])
    axes[idx].set_xlabel('Valor')
    axes[idx].set_title(f'Intervalos de Confianza - {var}', fontweight='bold')
    axes[idx].legend()
    axes[idx].grid(True, alpha=0.3)

plt.suptitle('COMPARACIÓN DE INTERVALOS DE CONFIANZA', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()

# GUARDAR GRÁFICO 8
plt.savefig('09_intervalos_confianza.png', dpi=300, bbox_inches='tight')
print("\n✅ Gráfico guardado: 09_intervalos_confianza.png")
plt.show()

# Impacto del tamaño muestral
print("\n📊 IMPACTO DEL TAMAÑO MUESTRAL EN IC:")
tamanos = [30, 50, 100, 150]
for n in tamanos:
    muestra = np.random.choice(df['Horas_Sueno'], size=n, replace=False)
    ic = calcular_ic(muestra, 'Horas_Sueno', 0.95)
    print(f"n={n}: IC=({ic['ic_inf']:.2f}, {ic['ic_sup']:.2f}), Amplitud={ic['ic_sup']-ic['ic_inf']:.2f}")

print("\n✅ SECCIÓN 8 COMPLETADA")

# ============================================
# 9. PRUEBAS DE HIPÓTESIS
# ============================================

print("\n" + "="*60)
print("PRUEBAS DE HIPÓTESIS")
print("="*60)

# 9.1 Prueba t para una muestra - Horas de sueño
print("\n📊 PRUEBA t PARA UNA MUESTRA - Horas de sueño")
print("H₀: μ = 7 horas (los estudiantes duermen las 7 horas recomendadas)")
print("H₁: μ ≠ 7 horas")

muestra_sueno = df['Horas_Sueno']
t_stat, p_valor = stats.ttest_1samp(muestra_sueno, 7)

print(f"Estadístico t = {t_stat:.3f}")
print(f"Valor p = {p_valor:.4f}")
print(f"Grados de libertad = {len(muestra_sueno)-1}")
print(f"Media muestral = {muestra_sueno.mean():.2f}")

alpha = 0.05
if p_valor < alpha:
    print(f"✅ Decisión: Rechazar H₀ (p < {alpha})")
    print("Conclusión: Hay evidencia suficiente para afirmar que el promedio de horas de sueño es diferente a 7 horas.")
else:
    print(f"❌ Decisión: No rechazar H₀ (p > {alpha})")
    print("Conclusión: No hay evidencia suficiente para afirmar que el promedio de horas de sueño sea diferente a 7 horas.")

# 9.2 Prueba para proporción - Actividad física
print("\n📊 PRUEBA PARA PROPORCIÓN - Actividad física")
print("H₀: p = 0.40 (40% hace actividad física regular)")
print("H₁: p < 0.40")

p0 = 0.40
p_hat = (df['AF_Regular'] == 'Sí').mean()
n = len(df)

# Estadístico z
z_stat = (p_hat - p0) / np.sqrt(p0 * (1-p0) / n)
p_valor_prop = stats.norm.cdf(z_stat)  # prueba unilateral izquierda

print(f"Proporción observada = {p_hat:.3f} ({p_hat*100:.1f}%)")
print(f"Estadístico z = {z_stat:.3f}")
print(f"Valor p = {p_valor_prop:.4f}")

if p_valor_prop < alpha:
    print(f"✅ Decisión: Rechazar H₀ (p < {alpha})")
    print("Conclusión: Hay evidencia de que menos del 40% realiza actividad física regular.")
else:
    print(f"❌ Decisión: No rechazar H₀ (p > {alpha})")
    print("Conclusión: No hay evidencia de que menos del 40% realice actividad física regular.")

# 9.3 Comparación de medias - Salud vs Otras facultades
print("\n📊 COMPARACIÓN DE MEDIAS - Salud vs Otras facultades")
print("Variable: Horas de sueño")

salud = df[df['Facultad'] == 'Ciencias de la Salud']['Horas_Sueno']
otras = df[df['Facultad'] != 'Ciencias de la Salud']['Horas_Sueno']

print(f"\nCiencias de la Salud (n={len(salud)}):")
print(f"  Media = {salud.mean():.2f}, Desv.est = {salud.std():.2f}")
print(f"Otras facultades (n={len(otras)}):")
print(f"  Media = {otras.mean():.2f}, Desv.est = {otras.std():.2f}")

# Prueba t para muestras independientes
t_stat_2, p_valor_2 = stats.ttest_ind(salud, otras, equal_var=False)

print(f"\nEstadístico t = {t_stat_2:.3f}")
print(f"Valor p = {p_valor_2:.4f}")

if p_valor_2 < alpha:
    print(f"✅ Decisión: Rechazar H₀ (p < {alpha})")
    print("Conclusión: Existe diferencia significativa en horas de sueño entre facultades.")
else:
    print(f"❌ Decisión: No rechazar H₀ (p > {alpha})")
    print("Conclusión: No existe diferencia significativa en horas de sueño entre facultades.")

# 9.4 ANOVA - Comparación múltiple de facultades
print("\n📊 ANOVA - Comparación de todas las facultades")
print("Variable dependiente: Horas de sueño")
print("Factor: Facultad")

from scipy.stats import f_oneway

grupos = [df[df['Facultad'] == fac]['Horas_Sueno'] for fac in df['Facultad'].unique()]
f_stat, p_valor_anova = f_oneway(*grupos)

print(f"Estadístico F = {f_stat:.3f}")
print(f"Valor p = {p_valor_anova:.4f}")

if p_valor_anova < alpha:
    print("✅ Decisión: Rechazar H₀")
    print("Conclusión: Al menos una facultad tiene promedio de sueño diferente.")
else:
    print("❌ Decisión: No rechazar H₀")
    print("Conclusión: No hay diferencias significativas entre facultades.")

# 9.5 Visualización de pruebas de hipótesis
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Gráfico 1: Distribución t para prueba de sueño
x_t = np.linspace(-4, 4, 100)
y_t = stats.t.pdf(x_t, len(muestra_sueno)-1)
axes[0,0].plot(x_t, y_t, 'b-', linewidth=2)
axes[0,0].axvline(t_stat, color='red', linewidth=2, label=f't observado = {t_stat:.2f}')
axes[0,0].axvline(-1.984, color='green', linestyle='--', label='Valor crítico ±1.984')
axes[0,0].axvline(1.984, color='green', linestyle='--')
axes[0,0].fill_between(x_t, y_t, where=(x_t < -1.984) | (x_t > 1.984),
                        alpha=0.3, color='red', label='Región de rechazo (α=0.05)')
axes[0,0].set_title('Prueba t - Horas de sueño', fontweight='bold')
axes[0,0].set_xlabel('t')
axes[0,0].set_ylabel('Densidad')
axes[0,0].legend()
axes[0,0].grid(True, alpha=0.3)

# Gráfico 2: Boxplot comparativo
sns.boxplot(data=df, x='Facultad', y='Horas_Sueno', ax=axes[0,1])
axes[0,1].set_title('Horas de sueño por Facultad', fontweight='bold')
axes[0,1].tick_params(axis='x', rotation=45)

# Gráfico 3: Distribución de proporciones
x_prop = np.linspace(0.2, 0.6, 100)
y_prop = stats.norm.pdf(x_prop, p0, np.sqrt(p0*(1-p0)/n))
axes[1,0].plot(x_prop, y_prop, 'b-', linewidth=2)
axes[1,0].axvline(p_hat, color='red', linewidth=2, label=f'p̂ observado = {p_hat:.2f}')
axes[1,0].axvline(p0, color='green', linestyle='--', label='p₀ = 0.40')
axes[1,0].fill_between(x_prop, y_prop, where=(x_prop < p_hat),
                        alpha=0.3, color='red', label=f'p-valor = {p_valor_prop:.3f}')
axes[1,0].set_title('Prueba de proporción - Actividad física', fontweight='bold')
axes[1,0].set_xlabel('Proporción')
axes[1,0].set_ylabel('Densidad')
axes[1,0].legend()
axes[1,0].grid(True, alpha=0.3)

# Gráfico 4: Intervalos de confianza comparativos
medias_fac = df.groupby('Facultad')['Horas_Sueno'].agg(['mean', 'std', 'count']).reset_index()
for i, row in medias_fac.iterrows():
    error = 1.96 * row['std'] / np.sqrt(row['count'])
    axes[1,1].errorbar(row['mean'], i, xerr=error, fmt='o', capsize=5,
                       label=row['Facultad'])
axes[1,1].axvline(mu_pob, color='red', linestyle='--', label=f'Media global = {mu_pob:.2f}')
axes[1,1].set_yticks(range(len(medias_fac)))
axes[1,1].set_yticklabels(medias_fac['Facultad'])
axes[1,1].set_xlabel('Horas de sueño')
axes[1,1].set_title('Intervalos de confianza (95%) por facultad', fontweight='bold')
axes[1,1].legend()
axes[1,1].grid(True, alpha=0.3)

plt.suptitle('PRUEBAS DE HIPÓTESIS - VISUALIZACIONES', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()

# GUARDAR GRÁFICO 9
plt.savefig('10_pruebas_hipotesis.png', dpi=300, bbox_inches='tight')
print("\n✅ Gráfico guardado: 10_pruebas_hipotesis.png")
plt.show()

print("\n✅ SECCIÓN 9 COMPLETADA")

"""De"""

# ============================================
# 10. INFORME FINAL Y EXPORTACIÓN
# ============================================

print("\n" + "="*60)
print("INFORME FINAL - CONCLUSIONES")
print("="*60)

# Resumen ejecutivo
print("""
📋 RESUMEN EJECUTIVO
=====================
Se realizó un estudio sobre hábitos saludables en 150 estudiantes universitarios,
analizando variables de sueño, alimentación, actividad física y estrés.

PRINCIPALES HALLAZGOS:
""")

# Hallazgo 1: Sueño
media_sueno = df['Horas_Sueno'].mean()
if media_sueno < 6.5:
    print(f"🔴 SUEÑO: Promedio de {media_sueno:.1f} horas - Por debajo de lo recomendado")
elif media_sueno < 7.5:
    print(f"🟡 SUEÑO: Promedio de {media_sueno:.1f} horas - Dentro del rango aceptable")
else:
    print(f"🟢 SUEÑO: Promedio de {media_sueno:.1f} horas - Óptimo")

# Hallazgo 2: Actividad física
p_af = (df['AF_Regular'] == 'Sí').mean()
if p_af < 0.3:
    print(f"🔴 ACTIVIDAD FÍSICA: Solo {p_af*100:.1f}% - Muy bajo")
elif p_af < 0.4:
    print(f"🟡 ACTIVIDAD FÍSICA: {p_af*100:.1f}% - Moderado")
else:
    print(f"🟢 ACTIVIDAD FÍSICA: {p_af*100:.1f}% - Bueno")

# Hallazgo 3: Estrés
media_estres = df['Estres'].mean()
if media_estres > 7:
    print(f"🔴 ESTRÉS: Nivel {media_estres:.1f}/10 - Alto")
elif media_estres > 5:
    print(f"🟡 ESTRÉS: Nivel {media_estres:.1f}/10 - Moderado")
else:
    print(f"🟢 ESTRÉS: Nivel {media_estres:.1f}/10 - Bajo")

# Hallazgo 4: Alimentación
media_comida = df['Comida_Rapida'].mean()
if media_comida > 4:
    print(f"🔴 ALIMENTACIÓN: {media_comida:.1f} días/semana comida rápida - Excesivo")
elif media_comida > 2:
    print(f"🟡 ALIMENTACIÓN: {media_comida:.1f} días/semana comida rápida - Moderado")
else:
    print(f"🟢 ALIMENTACIÓN: {media_comida:.1f} días/semana comida rápida - Bueno")

# Recomendaciones
print("""

🎯 RECOMENDACIONES
==================
1. Implementar programas de manejo del estrés (talleres de mindfulness)
2. Crear horarios deportivos flexibles adaptados a carga académica
3. Ofrecer opciones de alimentación saludable en cafeterías
4. Realizar campañas de concientización sobre higiene del sueño
5. Establecer un sistema de apoyo psicológico accesible

📊 ESTADÍSTICAS CLAVE
=====================""")
print(f"• Total estudiantes: {len(df)}")
print(f"• Edad promedio: {df['Edad'].mean():.1f} años")
print(f"• Horas sueño promedio: {media_sueno:.2f} ± {df['Horas_Sueno'].std():.2f}")
print(f"• % Actividad física regular: {p_af*100:.1f}%")
print(f"• Nivel estrés promedio: {media_estres:.1f}/10")
print(f"• IMC promedio: {df['IMC'].mean():.1f}")
print(f"• % Consume alcohol: {(df['Consume_Alcohol'] == 'Sí').mean()*100:.1f}%")
print(f"• % Fuma: {(df['Fuma'] == 'Sí').mean()*100:.1f}%")

# Exportar datos
print("\n💾 EXPORTANDO DATOS...")

# Guardar dataset
df.to_csv('dataset_habitos_saludables.csv', index=False)
print("✅ Dataset guardado: dataset_habitos_saludables.csv")

# Guardar diccionario
diccionario.to_csv('diccionario_variables.csv', index=False)
print("✅ Diccionario guardado: diccionario_variables.csv")

# Guardar estadísticas
estadisticas.to_csv('estadisticas_descriptivas.csv')
print("✅ Estadísticas guardadas: estadisticas_descriptivas.csv")

# Crear resumen en markdown
with open('informe_final.md', 'w', encoding='utf-8') as f:
    f.write("# INFORME FINAL: HÁBITOS SALUDABLES EN JÓVENES UNIVERSITARIOS\n\n")
    f.write("## Metodología\n")
    f.write(f"* **Muestra:** {len(df)} estudiantes\n")
    f.write(f"* **Facultades:** {', '.join(df['Facultad'].unique())}\n")
    f.write(f"* **Variables analizadas:** {len(df.columns)}\n\n")
    f.write("## Resultados Principales\n")
    f.write(f"* Sueño promedio: {media_sueno:.2f} horas\n")
    f.write(f"* Actividad física regular: {p_af*100:.1f}%\n")
    f.write(f"* Estrés promedio: {media_estres:.1f}/10\n")
    f.write(f"* Comida rápida: {media_comida:.1f} días/semana\n")
    f.write(f"* IMC promedio: {df['IMC'].mean():.1f}\n")

print("✅ Informe guardado: informe_final.md")

print("\n" + "="*60)
print("🎉 ANÁLISIS COMPLETADO EXITOSAMENTE")
print("="*60)

# ============================================
# DESCARGAR TODOS LOS GRÁFICOS GUARDADOS
# ============================================

from google.colab import files
import os

print("\n" + "="*60)
print("⬇️ DESCARGANDO TODOS LOS GRÁFICOS")
print("="*60)

# Lista de gráficos guardados
graficos = [
    '01_histogramas_completos.png',
    '02_boxplots_completos.png',
    '03_barras_categoricas.png',
    '04_mapa_calor_correlaciones.png',
    '05_dispersion_completa.png',
    '06_distribucion_normal_sueno.png',
    '07_distribucion_binomial_comida.png',
    '08_teorema_limite_central.png',
    '09_intervalos_confianza.png',
    '10_pruebas_hipotesis.png'
]

# Verificar y descargar
for grafico in graficos:
    if os.path.exists(grafico):
        print(f"📤 Descargando: {grafico}")
        files.download(grafico)
    else:
        print(f"❌ No encontrado: {grafico}")

print("\n✅ DESCARGA COMPLETADA")